bot_name: "SupportBot"
version: "1.0.0"
environment: "development"

llm:
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout: 30
  api_key_env: "OPENAI_API_KEY"
  base_url: null

conversation:
  max_context_length: 10
  context_window_tokens: 4000
  enable_memory: true
  memory_decay_turns: 20
  greeting_enabled: true
  fallback_enabled: true
  max_retries: 3

prompts:
  system_prompt_template: "default_system_prompt"
  user_prompt_template: "default_user_prompt"
  chain_of_thought_enabled: true
  reasoning_prefix: "Let me think about this step by step:"
  confidence_threshold: 0.7
  include_examples: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/chatbot.log"
  max_file_size: 10485760
  backup_count: 5
  log_conversations: true

security:
  enable_content_filter: true
  max_input_length: 2000
  rate_limit_requests: 100
  rate_limit_window: 3600
  blocked_patterns:
    - "spam"
    - "abuse"
    - "harmful"
